# Generated by Django 4.1.2 on 2022-10-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amazon', models.CharField(max_length=300)),
                ('elitehub', models.CharField(max_length=300)),
                ('flipkart', models.CharField(max_length=300)),
                ('imagelink', models.CharField(max_length=300)),
            ],
        ),
    ]
